name: Staging squirrel deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@1.0.5
        id: versioning
        with:
          releaseType: patch
          incrementPerCommit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Next Release Number
        run: echo ${{ steps.versioning.outputs.version }}

      - name: Tag release
        shell: bash
        run: |
          echo ${{steps.versioning.outputs.version}}
          git tag ${{steps.versioning.outputs.version}}
          git push origin ${{steps.versioning.outputs.version}}
          echo "Pushed tag ${{steps.versioning.outputs.version}}"
          


