name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Running Step 1"

      - name: Step 2
        run: echo "Running Step 2"

      # Add more steps as needed

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Step 3
        run: echo "Running Step 3"

      - name: Step 4
        run: echo "Running Step 4"

      # Add more steps as needed
