name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run Third Workflow
        id: third_workflow
        uses: ./.github/workflows/third.yml

      - name: Step 4
        run: echo "Running Step 4"

      - name: Step 5
        run: echo "Running Step 5"

      - name: Step 6
        run: echo "Running Step 6"

      - name: Access Third Workflow Output
        run: echo "Third Workflow Output ${{ steps.third_workflow.outputs.my_output }}"
