name: Second Workflow

on:
  push:
    branches:
      - main

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Inside Second File
        run: echo "Inside Second File"
      # Add more steps as needed
