name: Second Workflow

on:
  push:
    branches:
      - main

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run Third Workflow
        id: third_workflow
        uses: ./.github/workflows/third.yml

      - name: Step 7
        run: echo "Running Step 7"

      - name: Step 8
        run: echo "Running Step 8"

      - name: Step 9
        run: echo "Running Step 9"

      - name: Access Third Workflow Output
        run: 
          echo "Third Workflow Output ${{ steps.third_workflow.outputs.my_output }}"
