name: Second Workflow

on:
  push:
    branches:
      - main

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 5
        run: echo "Running Step 5"

      - name: Step 6
        run: echo "Running Step 6"

      # Add more steps as needed
