name: Third Workflow

on:
  push:
    branches:
      - main

jobs:
  third_job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Running Step 1"

      - name: Step 2
        run: echo "Running Step 2"

      - name: Step 3
        run: echo "Running Step 3"

      - name: Set Output
        id: output_step
        run: echo "::set-output name=my_output::Hello World"

    outputs:
      my_output: ${{ steps.output_step.outputs.my_output }}
